#! /usr/bin/env python
import sys
from balihoosimulator import BalihooSimulator

def usage():
    print("%s <url>" % (sys.argv[0],))

def main():
    if len(sys.argv) > 1:
        bs = BalihooSimulator(sys.argv[1])
        return bs.make_requests()
    else:
        usage()

if __name__ == "__main__":
    sys.exit(main())

